# Configuration Prometheus pour la plateforme E-Commerce
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-mÃªme
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Service Membership (Users)
  - job_name: 'ms-membership'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ms-membership'

  # Service Product
  - job_name: 'ms-product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ms-product'

  # Service Order
  - job_name: 'ms-order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ms-order'
